apiVersion: v1
kind: Template
metadata:
  name: cvms
  annotations:
    openshift.io/display-name: "CI/CD EBIS (Ephemeral)"
    description: "Ephemeral Ebis container for API testing. WARNING: Any data stored will be lost upon pod destruction."
    template.openshift.io/long-description: "This template defines the container needed to Behaviour Drivern API Testsrun automated tests."
    iconClass: "icon-apache"
    tags: "ebis, cvms"
    template.openshift.io/provider-display-name: "Platform Capabilities Team"
labels:
  template: cvms
objects:
- kind: "ImageStream"
  apiVersion: "v1"
  metadata:
    name: "${SERVICE_NAME}"
    annotations:
      description: "Keeps track of changes in the ebis image"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${SERVICE_NAME}"
    annotations:
      description: "Builds the ebis base container."
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    resources:
      limits:
        cpu: "2000m"
        memory: "2048Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
    source:
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      sourceSecret:
        name: Zikiwe!1
    strategy:
      dockerStrategy:
        dockerfilePath: build.docker
    output:
      to:
        kind: "ImageStreamTag"
        name: "${SERVICE_NAME}:${VERSION}"
    triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
        - "ebis"
        from:
          kind: "ImageStreamTag"
          name: "${SERVICE_NAME}:${VERSION}"
          namespace: "${NAMESPACE}"
parameters:
- name: "NAMESPACE"
  displayName: "Namespace"
  required: true
  description: "The OpenShift Namespace where the ImageStream resides."
  value: "ebis-dev"
- name: "SERVICE_NAME"
  displayName: "Service name"
  required: true
  description: "The OpenShift service name."
  value: "ebis"
- name: "REGISTRY_URL"
  displayName: "Docker registry URL"
  required: true
  description: "The OpenShift docker registry URL from which to pull images for deployments."
  value: " "
- name: "BUGTRACKER_URL"
  displayName: "Bug Tracker URL"
  description: "The URL of the bug tracker for CI/CD problems."
# value: "http://jira.vodacom.co.za/projects/BDPS/"
- name: "DOCUMENTATION_URL"
  displayName: "Documentation URL"
  description: "The URL where the documentation is available."
# value: "http://confluence.vodacom.co.za/display/BDPSA/Continuous+Integration%2C+Testing+and+Deployment"
- name: "SOURCE_REPOSITORY_URL"
  displayName: "Git Repository URL"
  description: "The URL of the repository with the OpenShift templates."
#  value: "https://pbdpgl1zafsrh.vodacom.corp/cicd/bustel_ocp.git"
  value: "https://github.com/Kwenene/javaAndMaven.git"
- name: "SOURCE_REPOSITORY_REF"
  displayName: "Git Reference"
  description: "Set this to a branch name, tag or other ref of your repository if you are not using the default branch."
  value: "ebis_branch"
- name: "VERSION"
  displayName: "Ebis version"
  required: true
  description: "The version of Ebis."
  value: "1.0"
  #ignore-https-gitconf

